preserve_hierarchy: true
commit_message: "chore(i18n): update translations from Crowdin"
append_commit_message: false

files:
  - source: /src/i18n/locales/en/messages.po
    translation: /src/i18n/locales/%locale%/messages.po
    languages_mapping:
      locale:
        zh-CN: zh-Hans
